import {env} from 'cloudflare:workers';
const db=()=>{if(!env.DB)throw Error('Database unavailable');return env.DB};
const text=(v:unknown,max=150)=>typeof v==='string'?v.trim().slice(0,max):'';
const num=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:NaN;
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'});
const dateOK=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
const addDays=(date:string,n:number)=>new Date(Date.parse(date+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
const bad=(error:string,status=400)=>Response.json({error},{status});
function fail(e:unknown){console.error('Gym API',e);const m=e instanceof Error?e.message:'';return bad(m.includes('UNIQUE')?'This record already exists. Check email, attendance or class registration.':'Unable to complete the request. Please retry.',m.includes('UNIQUE')?409:500)}
export async function GET(request:Request){try{const d=db(),q=new URL(request.url).searchParams,day=today();
if(q.get('memberId')){const id=text(q.get('memberId'),40),member=await d.prepare('SELECT * FROM members WHERE id=?').bind(id).first();if(!member)return bad('Member not found.',404);const [ms,p,c,r]=await d.batch([d.prepare('SELECT ms.*,p.name AS plan_name FROM memberships ms JOIN plans p ON p.id=ms.plan_id WHERE ms.member_id=? ORDER BY ms.start_date DESC').bind(id),d.prepare('SELECT p.*,ms.member_id FROM payments p JOIN memberships ms ON ms.id=p.membership_id WHERE ms.member_id=? ORDER BY p.created_at DESC').bind(id),d.prepare('SELECT * FROM checkins WHERE member_id=? ORDER BY checked_at DESC LIMIT 30').bind(id),d.prepare('SELECT r.*,c.title,c.trainer,c.starts_at,c.status FROM registrations r JOIN classes c ON c.id=r.class_id WHERE r.member_id=? ORDER BY c.starts_at DESC').bind(id)]);return Response.json({member,memberships:ms.results,payments:p.results,checkins:c.results,registrations:r.results})}
const [m,p,ms,c,r,a,pay]=await d.batch([d.prepare("SELECT m.*,EXISTS(SELECT 1 FROM memberships ms WHERE ms.member_id=m.id AND ms.start_date<=? AND ms.end_date>=?) AS has_access,(SELECT MAX(end_date) FROM memberships ms WHERE ms.member_id=m.id) AS expires,(SELECT COALESCE(SUM(amount_cents-paid_cents),0) FROM memberships ms WHERE ms.member_id=m.id) AS balance_cents FROM members m ORDER BY m.joined_at DESC LIMIT 1000").bind(day,day),d.prepare('SELECT * FROM plans ORDER BY days'),d.prepare('SELECT ms.*,m.name AS member_name,m.code,p.name AS plan_name FROM memberships ms JOIN members m ON m.id=ms.member_id JOIN plans p ON p.id=ms.plan_id ORDER BY ms.created_at DESC LIMIT 1000'),d.prepare('SELECT c.*,(SELECT COUNT(*) FROM registrations r WHERE r.class_id=c.id) AS booked FROM classes c ORDER BY c.starts_at DESC LIMIT 300'),d.prepare('SELECT r.*,m.name AS member_name,m.code FROM registrations r JOIN members m ON m.id=r.member_id'),d.prepare('SELECT a.*,m.name AS member_name,m.code FROM checkins a JOIN members m ON m.id=a.member_id ORDER BY a.checked_at DESC LIMIT 500'),d.prepare('SELECT p.*,m.name AS member_name,m.code,pl.name AS plan_name FROM payments p JOIN memberships ms ON ms.id=p.membership_id JOIN members m ON m.id=ms.member_id JOIN plans pl ON pl.id=ms.plan_id ORDER BY p.created_at DESC LIMIT 1000')]);return Response.json({members:m.results,plans:p.results,memberships:ms.results,classes:c.results,registrations:r.results,checkins:a.results,payments:pay.results,today:day})
}catch(e){return fail(e)}}
export async function POST(request:Request){let b:Record<string,unknown>;try{b=await request.json() as Record<string,unknown>}catch{return bad('Invalid JSON.')}try{const d=db(),now=new Date().toISOString(),day=today(),id=text(b.id,40);
if(b.action==='member'){const name=text(b.name,100),email=text(b.email,120).toLowerCase(),phone=text(b.phone,30);if(!name||!/^\S+@\S+\.\S+$/.test(email)||phone.length<7)return bad('Enter a name, valid email and phone.');if(id){const r=await d.prepare('UPDATE members SET name=?,email=?,phone=? WHERE id=?').bind(name,email,phone,id).run();if(!r.meta.changes)return bad('Member not found.',404)}else await d.prepare("INSERT INTO members VALUES(?,?,?,?,?,'Active',?)").bind(crypto.randomUUID(),'IC-'+crypto.randomUUID().slice(0,6).toUpperCase(),name,email,phone,now).run();return Response.json({message:id?'Member updated.':'Member added.'})}
if(b.action==='memberStatus'){const status=text(b.status,20);if(!['Active','Suspended','Archived'].includes(status))return bad('Invalid status.');const r=await d.prepare('UPDATE members SET status=? WHERE id=?').bind(status,id).run();return r.meta.changes?Response.json({message:'Status updated.'}):bad('Member not found.',404)}
if(b.action==='plan'){const name=text(b.name,80),days=num(b.days),price=num(b.priceCents);if(!name||!Number.isInteger(days)||days<1||days>730||!Number.isInteger(price)||price<100||price>1e8)return bad('Enter a plan name, 1–730 days and a valid price.');await d.prepare('INSERT INTO plans VALUES(?,?,?,?,1)').bind(crypto.randomUUID(),name,days,price).run();return Response.json({message:'Plan added.'})}
if(b.action==='planStatus'){const active=num(b.active);if(![0,1].includes(active))return bad('Invalid plan status.');await d.prepare('UPDATE plans SET active=? WHERE id=?').bind(active,id).run();return Response.json({message:'Plan availability updated.'})}
if(b.action==='membership'){const memberId=text(b.memberId,40),planId=text(b.planId,40),start=text(b.startDate,10);if(!dateOK(start)||start<day)return bad('Membership must start today or later.');const member=await d.prepare("SELECT id FROM members WHERE id=? AND status='Active'").bind(memberId).first(),plan=await d.prepare('SELECT * FROM plans WHERE id=? AND active=1').bind(planId).first<{days:number;price_cents:number}>();if(!member||!plan)return bad('Choose an active member and available plan.');const end=addDays(start,plan.days-1);const r=await d.prepare("INSERT INTO memberships(id,member_id,plan_id,start_date,end_date,amount_cents,paid_cents,created_at) SELECT ?,?,?,?,?,?,0,? WHERE NOT EXISTS(SELECT 1 FROM memberships WHERE member_id=? AND start_date<=? AND end_date>=?) AND EXISTS(SELECT 1 FROM members WHERE id=? AND status='Active') AND EXISTS(SELECT 1 FROM plans WHERE id=? AND active=1)").bind(crypto.randomUUID(),memberId,planId,start,end,plan.price_cents,now,memberId,end,start,memberId,planId).run();return r.meta.changes?Response.json({message:'Membership assigned.'}):bad('Membership overlaps an existing period or the member/plan is unavailable.',409)}
if(b.action==='payment'){const membershipId=text(b.membershipId,40),amount=num(b.amountCents),method=text(b.method,30);if(!Number.isInteger(amount)||amount<1||!['Cash','GCash','Bank transfer','Card terminal'].includes(method))return bad('Enter a valid amount and payment method.');const paymentId=crypto.randomUUID(),reference='PAY-'+crypto.randomUUID().slice(0,8).toUpperCase();const r=await d.batch([d.prepare('INSERT INTO payments(id,membership_id,amount_cents,method,reference,created_at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM memberships WHERE id=? AND amount_cents-paid_cents>=?)').bind(paymentId,membershipId,amount,method,reference,now,membershipId,amount),d.prepare('UPDATE memberships SET paid_cents=paid_cents+? WHERE id=? AND EXISTS(SELECT 1 FROM payments WHERE id=?)').bind(amount,membershipId,paymentId)]);return r[0].meta.changes?Response.json({message:'Payment recorded.',reference}):bad('Amount exceeds the remaining balance or membership is unavailable.',409)}
if(b.action==='checkin'){const r=await d.prepare("INSERT INTO checkins(id,member_id,day,checked_at) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM members m JOIN memberships ms ON ms.member_id=m.id WHERE m.id=? AND m.status='Active' AND ms.start_date<=? AND ms.end_date>=?)").bind(crypto.randomUUID(),id,day,now,id,day,day).run();return r.meta.changes?Response.json({message:'Check-in recorded.'}):bad('Check-in requires an active member with a current membership.',409)}
if(b.action==='class'){const title=text(b.title,80),trainer=text(b.trainer,80),starts=text(b.startsAt,40),duration=num(b.duration),capacity=num(b.capacity);if(!title||!trainer||!Number.isFinite(Date.parse(starts))||Date.parse(starts)<=Date.now()||!Number.isInteger(duration)||duration<15||duration>240||!Number.isInteger(capacity)||capacity<1||capacity>200)return bad('Enter a future class, trainer, 15–240 minutes and capacity 1–200.');await d.prepare("INSERT INTO classes VALUES(?,?,?,?,?,?,'Scheduled')").bind(crypto.randomUUID(),title,trainer,new Date(starts).toISOString(),duration,capacity).run();return Response.json({message:'Class scheduled.'})}
if(b.action==='classStatus'){const status=text(b.status,20);if(!['Scheduled','Cancelled'].includes(status))return bad('Invalid class status.');await d.prepare('UPDATE classes SET status=? WHERE id=?').bind(status,id).run();return Response.json({message:'Class status updated.'})}
if(b.action==='register'){const memberId=text(b.memberId,40),classId=text(b.classId,40),c=await d.prepare('SELECT starts_at FROM classes WHERE id=?').bind(classId).first<{starts_at:string}>();if(!c)return bad('Class not found.',404);const classDay=new Date(c.starts_at).toLocaleDateString('en-CA',{timeZone:'Asia/Manila'});const r=await d.prepare("INSERT INTO registrations(id,class_id,member_id,created_at) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM classes c WHERE c.id=? AND c.status='Scheduled' AND datetime(c.starts_at)>datetime(?) AND (SELECT COUNT(*) FROM registrations r WHERE r.class_id=c.id)<c.capacity) AND EXISTS(SELECT 1 FROM members m JOIN memberships ms ON ms.member_id=m.id WHERE m.id=? AND m.status='Active' AND ms.start_date<=? AND ms.end_date>=?) AND NOT EXISTS(SELECT 1 FROM registrations r JOIN classes c ON c.id=r.class_id JOIN classes target ON target.id=? WHERE r.member_id=? AND c.status='Scheduled' AND datetime(c.starts_at)<datetime(target.starts_at,'+'||target.duration||' minutes') AND datetime(c.starts_at,'+'||c.duration||' minutes')>datetime(target.starts_at))").bind(crypto.randomUUID(),classId,memberId,now,classId,now,memberId,classDay,classDay,classId,memberId).run();return r.meta.changes?Response.json({message:'Member booked into class.'}):bad('Class is full, unavailable, overlaps another booking, or membership does not cover the class date.',409)}
if(b.action==='unregister'){const r=await d.prepare('DELETE FROM registrations WHERE id=? AND EXISTS(SELECT 1 FROM classes c WHERE c.id=registrations.class_id AND datetime(c.starts_at)>datetime(?))').bind(id,now).run();return r.meta.changes?Response.json({message:'Class booking removed.'}):bad('Past class bookings cannot be removed.',409)}
if(b.action==='seed'){if(await d.prepare('SELECT id FROM members LIMIT 1').first())return bad('Sample data is available only for an empty member list.',409);const plans=[{id:crypto.randomUUID(),name:'Monthly Essential',days:30,price:150000},{id:crypto.randomUUID(),name:'Quarterly Unlimited',days:90,price:390000},{id:crypto.randomUUID(),name:'Annual Performance',days:365,price:1440000}];const names=['Alex Rivera','Jamie Santos','Morgan Reyes','Casey Cruz','Sam Garcia','Taylor Lim','Jordan Aquino','Riley Tan','Chris Mendoza','Drew Ramos','Avery Dela Cruz','Pat Flores'];const stmts=plans.map(p=>d.prepare('INSERT INTO plans VALUES(?,?,?,?,1)').bind(p.id,p.name,p.days,p.price));for(const [i,name] of names.entries()){const mid=crypto.randomUUID(),msid=crypto.randomUUID(),p=plans[i%3],start=addDays(day,i===2?-370:i===5?-360:i===0?-25:-10),end=addDays(start,p.days-1),amount=i%4===0?Math.floor(p.price/2):p.price;stmts.push(d.prepare("INSERT INTO members VALUES(?,?,?,?,?,'Active',?)").bind(mid,'IC-'+String(i+1001),name,name.toLowerCase().replaceAll(' ','.')+'@example.com','0917000'+String(i+1000),now),d.prepare('INSERT INTO memberships VALUES(?,?,?,?,?,?,?,?)').bind(msid,mid,p.id,start,end,p.price,amount,now),d.prepare('INSERT INTO payments VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),msid,amount,'Cash','PAY-SAMPLE-'+i,now));if(i<5&&end>=day)stmts.push(d.prepare('INSERT INTO checkins VALUES(?,?,?,?)').bind(crypto.randomUUID(),mid,day,now))}for(let i=0;i<6;i++){const date=addDays(day,1+Math.floor(i/2)),start=new Date(date+'T'+(i%2?'18':'08')+':00:00+08:00').toISOString();stmts.push(d.prepare("INSERT INTO classes VALUES(?,?,?,?,?,?,'Scheduled')").bind(crypto.randomUUID(),['Strength Fundamentals','Yoga Flow','HIIT Circuit'][i%3],['Coach Mika','Coach Andre','Coach Bea'][i%3],start,60,12+i*2))}await d.batch(stmts);return Response.json({message:'Sample gym loaded.'})}
return bad('Unknown action.');
}catch(e){return fail(e)}}
