import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
import {readFileSync,readdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');
for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sql.exec(readFileSync('drizzle/'+f,'utf8'));
function prepare(text,args=[]){return {bind(...v){return prepare(text,v)},async first(){return sql.prepare(text).get(...args)||null},async all(){return {results:sql.prepare(text).all(...args)}},async run(){const r=sql.prepare(text).run(...args);return {meta:{changes:Number(r.changes)},results:[]}},text,args}}
const DB={prepare,async batch(stmts){sql.exec('BEGIN');try{const r=stmts.map(v=>{const p=sql.prepare(v.text);if(/^SELECT/i.test(v.text))return {results:p.all(...v.args),meta:{changes:0}};const x=p.run(...v.args);return {results:[],meta:{changes:Number(x.changes)}}});sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
globalThis.__gymTestEnv={DB};
const source=readFileSync('app/api/gym/route.ts','utf8').replace("import {env} from 'cloudflare:workers';",'const env=globalThis.__gymTestEnv;');
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const {GET,POST}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
async function post(body,status=200){const r=await POST(new Request('http://test/api/gym',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));assert.equal(r.status,status,await r.clone().text());return r.json()}
async function get(q=''){const r=await GET(new Request('http://test/api/gym'+q));assert.equal(r.status,200,await r.clone().text());return r.json()}
const oldError=console.error;console.error=()=>{};
await post({action:'seed'});await post({action:'seed'},409);let data=await get();assert.equal(data.members.length,12);assert.equal(data.plans.length,3);assert.equal(data.classes.length,6);
await post({action:'member',name:'Test One',email:'test1@example.com',phone:'09123456789'});
await post({action:'member',name:'Test Two',email:'test2@example.com',phone:'09123456780'});
await post({action:'member',name:'Duplicate',email:'test1@example.com',phone:'09123456789'},409);
data=await get();const one=data.members.find(m=>m.email==='test1@example.com'),two=data.members.find(m=>m.email==='test2@example.com'),plan=data.plans.find(p=>p.days===30),day=data.today;
await post({action:'checkin',id:one.id},409);
await post({action:'membership',memberId:one.id,planId:plan.id,startDate:day});
await post({action:'membership',memberId:two.id,planId:plan.id,startDate:day});
await post({action:'membership',memberId:one.id,planId:plan.id,startDate:day},409);
const detail=await get('?memberId='+one.id),ms=detail.memberships[0];
assert.equal(ms.end_date,new Date(Date.parse(day)+29*86400000).toISOString().slice(0,10));
await post({action:'payment',membershipId:ms.id,amountCents:50000,method:'Cash'});
await post({action:'payment',membershipId:ms.id,amountCents:ms.amount_cents,method:'Cash'},409);
let updated=await get('?memberId='+one.id);assert.equal(updated.memberships[0].paid_cents,50000);assert.equal(updated.payments.length,1);
await post({action:'payment',membershipId:ms.id,amountCents:ms.amount_cents-50000,method:'GCash'});
await post({action:'payment',membershipId:ms.id,amountCents:1,method:'Cash'},409);
await post({action:'checkin',id:one.id});await post({action:'checkin',id:one.id},409);
const tomorrow=new Date(Date.parse(day)+86400000).toISOString().slice(0,10);
await post({action:'class',title:'Capacity test',trainer:'Test Coach',startsAt:tomorrow+'T14:00:00+08:00',duration:60,capacity:1});
data=await get();const c=data.classes.find(c=>c.title==='Capacity test');
await post({action:'register',classId:c.id,memberId:one.id});
await post({action:'register',classId:c.id,memberId:two.id},409);
await post({action:'register',classId:c.id,memberId:one.id},409);
await post({action:'class',title:'Overlap test',trainer:'Test Coach',startsAt:tomorrow+'T14:30:00+08:00',duration:60,capacity:10});
data=await get();const overlapping=data.classes.find(c=>c.title==='Overlap test');await post({action:'register',classId:overlapping.id,memberId:one.id},409);
const registration=data.registrations.find(r=>r.class_id===c.id);await post({action:'unregister',id:registration.id});
await post({action:'register',classId:c.id,memberId:two.id});
await post({action:'classStatus',id:c.id,status:'Cancelled'});await post({action:'register',classId:c.id,memberId:one.id},409);
await post({action:'memberStatus',id:one.id,status:'Suspended'});await post({action:'register',classId:overlapping.id,memberId:one.id},409);
await post({action:'memberStatus',id:two.id,status:'Suspended'});await post({action:'checkin',id:two.id},409);
await post({action:'planStatus',id:plan.id,active:0});
await post({action:'membership',memberId:one.id,planId:plan.id,startDate:tomorrow},400);
await post({action:'class',title:'Invalid',trainer:'Coach',startsAt:'bad',duration:60,capacity:1},400);
console.error=oldError;
console.log('PASS: sample data, member uniqueness, membership access/overlap, payment balances, duplicate attendance, class capacity/conflicts, cancellation, suspension and validation.');
